{% set name = "wilds" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3606ecfa0e1b3bf614cc4668355493553067929eddf2786917e53e15db06ce12

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.19.1
    - outdated >=0.2.0
    - pandas >=1.1.0
    - pillow >=7.2.0
    - ogb >=1.2.6
    - pytz >=2020.4
    - pytorch >=1.7.0
    - torchvision >=0.8.2
    - tqdm >=4.53.0
    - scikit-learn >=0.20.0
    - scipy >=1.5.4
    - pytorch_geometric
    - pytorch_scatter

test:
  imports:
    - wilds

about:
  home: https://wilds.stanford.edu/
  summary: A benchmark of in-the-wild distribution shifts spanning diverse data modalities and applications, from tumor identification to wildlife monitoring to poverty mapping.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/p-lambda/wilds/

extra:
  recipe-maintainers:
    - kohpangwei
    - ssagawa
    - mlondschien
